import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        {children}

        <div className="dark">
            <div
                className="h-96 w-full dark:bg-black bg-white  dark:bg-grid-white/[0.2] bg-grid-black/[0.2] relative flex items-center justify-center">
                {/* Radial gradient for the container to give a faded look */}
                <div
                    className="absolute pointer-events-none inset-0 flex items-center justify-center dark:bg-black bg-white [mask-image:radial-gradient(ellipse_at_center,transparent_20%,black)]"></div>
                <footer
                    className="footer footer-center p-5 text-primary-content flex flex-col items-center justify-center text-center">
                    <aside className="flex flex-col items-center justify-center">
                        <img
                            src="https://yqxicxlxliqzxrzajydh.supabase.co/storage/v1/object/sign/Gallery/VNext.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJHYWxsZXJ5L1ZOZXh0LnN2ZyIsImlhdCI6MTcxMDUwNzAzMiwiZXhwIjozMzIxNDk3MTAzMn0.Me_Q0FMVxMxv1iW7Tsz5vi7fKBbBouf3T6_MNz-MDDU&t=2024-03-15T12%3A50%3A42.474Z"
                            alt="image"
                            width="80"
                            height="80"
                            className="mx-auto"
                        />

                        <p className="relative z-20 bg-gradient-to-b from-neutral-200 to-neutral-500 bg-clip-text py-5 text-sm md:text-lg font-bold text-transparent sm:text-sm text-center">
                            VNext Ltd. <br/>Providing the best gaming community since 2021
                        </p>

                        <p className="relative z-20 bg-gradient-to-b from-neutral-200 to-neutral-500 bg-clip-text py-2 font-bold text-transparent text-center">
                            Copyright © 2024 - All right reserved <br/> Designed,Coded and programmed
                            with ❤️ by Carnoval15 (discord)
                        </p>
                    </aside>
                </footer>

            </div>
        </div>
        </body>
        </html>
    );
}
